import './chart';
import './chat';
import './copy-button';
import './countdown';
import './gallery';
import './increment-value';
import './jquery.downCount.min.js';
import './listing-map';
import './main';
import './navbar';
import './validation';
import '/home/hippo/code/pepitob/yerba-mate-reviews/app/javascript/theme/main'
